### ISSUE TITLE
IndexError: pixel index out of range

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/stick-hero-activity#28] opened 2020-06-04 18:41 UTC
I found this bug on master as well however
![image](https://user-images.githubusercontent.com/48695438/83797639-a2d97480-a6ab-11ea-8eed-5d0566edf586.png)

_Originally posted by @srevinsaju in https://github.com/sugarlabs/stick-hero-activity/pull/27_

Not sure how to reproduce the bug; but neverthless, it happens :confused:

**Comment by Saumya-Mishra9129** [comment] 2020-07-21 16:01
I am not able to reproduce this one.

**Comment by JuiP** [comment] 2020-07-21 17:21
It doesnot happen each time, I could reproduce the bug but I'm not sure exactly which action led to it.

Edit - tested again after #25  is merged, does not occur. Scaling in [this](https://github.com/sugarlabs/stick-hero-activity/blob/63908204fb4a65b6e421e8a5bc61c47ddda9a76c/main.py#L787) line has fixed it.
@chimosky maybe this issue can be closed now that commit 10ef895 fixed it.

**Comment by quozl** [comment] 2020-07-22 02:47
Agreed, can close.  Per https://github.com/sugarlabs/stick-hero-activity/pull/27#issuecomment-648102500 it was fixed by https://github.com/sugarlabs/stick-hero-activity/pull/25, just no metadata to say so.

**Comment by chimosky** [comment] 2020-07-22 14:16
@JuiP said
>  @chimosky maybe this issue can be closed now that commit 10ef895 fixed it.

Yeah, closing now.

**Closed as completed by chimosky** 2020-07-22 14:16 UTC
